# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'animation_params.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AnimationParameters(object):
    def setupUi(self, AnimationParameters):
        AnimationParameters.setObjectName("AnimationParameters")
        AnimationParameters.resize(370, 238)
        AnimationParameters.setSizeGripEnabled(True)
        AnimationParameters.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(AnimationParameters)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label2 = QtWidgets.QLabel(AnimationParameters)
        self.label2.setObjectName("label2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label2)
        self.spinUpdateInterval = QtWidgets.QSpinBox(AnimationParameters)
        self.spinUpdateInterval.setMinimum(1)
        self.spinUpdateInterval.setMaximum(10000)
        self.spinUpdateInterval.setProperty("value", 100)
        self.spinUpdateInterval.setObjectName("spinUpdateInterval")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinUpdateInterval)
        self.label6 = QtWidgets.QLabel(AnimationParameters)
        self.label6.setObjectName("label6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label6)
        self.label5 = QtWidgets.QLabel(AnimationParameters)
        self.label5.setObjectName("label5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label5)
        self.label4 = QtWidgets.QLabel(AnimationParameters)
        self.label4.setObjectName("label4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label4)
        self.comboXmin = QtWidgets.QComboBox(AnimationParameters)
        self.comboXmin.setObjectName("comboXmin")
        self.comboXmin.addItem("")
        self.comboXmin.addItem("")
        self.comboXmin.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboXmin)
        self.comboXmax = QtWidgets.QComboBox(AnimationParameters)
        self.comboXmax.setObjectName("comboXmax")
        self.comboXmax.addItem("")
        self.comboXmax.addItem("")
        self.comboXmax.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboXmax)
        self.comboYmin = QtWidgets.QComboBox(AnimationParameters)
        self.comboYmin.setObjectName("comboYmin")
        self.comboYmin.addItem("")
        self.comboYmin.addItem("")
        self.comboYmin.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboYmin)
        self.comboYmax = QtWidgets.QComboBox(AnimationParameters)
        self.comboYmax.setObjectName("comboYmax")
        self.comboYmax.addItem("")
        self.comboYmax.addItem("")
        self.comboYmax.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboYmax)
        self.label = QtWidgets.QLabel(AnimationParameters)
        self.label.setObjectName("label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(AnimationParameters)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AnimationParameters)
        self.comboYmin.setCurrentIndex(1)
        self.comboYmax.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(AnimationParameters)

    def retranslateUi(self, AnimationParameters):
        _translate = QtCore.QCoreApplication.translate
        AnimationParameters.setWindowTitle(_translate("AnimationParameters", "Animation settings"))
        self.label2.setText(_translate("AnimationParameters", "Update interval (ms)"))
        self.label6.setText(_translate("AnimationParameters", "x min"))
        self.label5.setText(_translate("AnimationParameters", "x max"))
        self.label4.setText(_translate("AnimationParameters", "y min"))
        self.comboXmin.setItemText(0, _translate("AnimationParameters", "From 1st frame"))
        self.comboXmin.setItemText(1, _translate("AnimationParameters", "Overall x minimum value"))
        self.comboXmin.setItemText(2, _translate("AnimationParameters", "Adaptive"))
        self.comboXmax.setItemText(0, _translate("AnimationParameters", "From 1st frame"))
        self.comboXmax.setItemText(1, _translate("AnimationParameters", "Overall x maximum value"))
        self.comboXmax.setItemText(2, _translate("AnimationParameters", "Adaptive"))
        self.comboYmin.setItemText(0, _translate("AnimationParameters", "From 1st frame"))
        self.comboYmin.setItemText(1, _translate("AnimationParameters", "Overall y minimum value"))
        self.comboYmin.setItemText(2, _translate("AnimationParameters", "Adaptive"))
        self.comboYmax.setItemText(0, _translate("AnimationParameters", "From 1st frame"))
        self.comboYmax.setItemText(1, _translate("AnimationParameters", "Overall y maximum value"))
        self.comboYmax.setItemText(2, _translate("AnimationParameters", "Adaptive"))
        self.label.setText(_translate("AnimationParameters", "y max"))

