# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'custom_plots.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CustomPlots(object):
    def setupUi(self, CustomPlots):
        CustomPlots.setObjectName("CustomPlots")
        CustomPlots.resize(750, 350)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(CustomPlots)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(CustomPlots)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listPlots = QtWidgets.QListWidget(CustomPlots)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listPlots.sizePolicy().hasHeightForWidth())
        self.listPlots.setSizePolicy(sizePolicy)
        self.listPlots.setMinimumSize(QtCore.QSize(100, 0))
        self.listPlots.setBaseSize(QtCore.QSize(0, 0))
        self.listPlots.setAlternatingRowColors(True)
        self.listPlots.setObjectName("listPlots")
        self.verticalLayout.addWidget(self.listPlots)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonAddPlot = QtWidgets.QPushButton(CustomPlots)
        self.buttonAddPlot.setObjectName("buttonAddPlot")
        self.horizontalLayout_2.addWidget(self.buttonAddPlot)
        self.buttonRemovePlot = QtWidgets.QPushButton(CustomPlots)
        self.buttonRemovePlot.setObjectName("buttonRemovePlot")
        self.horizontalLayout_2.addWidget(self.buttonRemovePlot)
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(CustomPlots)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.editSourceCode = QtWidgets.QPlainTextEdit(CustomPlots)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editSourceCode.sizePolicy().hasHeightForWidth())
        self.editSourceCode.setSizePolicy(sizePolicy)
        self.editSourceCode.setMinimumSize(QtCore.QSize(400, 0))
        self.editSourceCode.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.editSourceCode.setObjectName("editSourceCode")
        self.verticalLayout_2.addWidget(self.editSourceCode)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.buttonSave = QtWidgets.QPushButton(CustomPlots)
        self.buttonSave.setObjectName("buttonSave")
        self.horizontalLayout_3.addWidget(self.buttonSave)
        self.buttonMakePlot = QtWidgets.QPushButton(CustomPlots)
        self.buttonMakePlot.setObjectName("buttonMakePlot")
        self.horizontalLayout_3.addWidget(self.buttonMakePlot)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)

        self.retranslateUi(CustomPlots)
        QtCore.QMetaObject.connectSlotsByName(CustomPlots)

    def retranslateUi(self, CustomPlots):
        _translate = QtCore.QCoreApplication.translate
        CustomPlots.setWindowTitle(_translate("CustomPlots", "User-defined plots"))
        self.label.setText(_translate("CustomPlots", "Plots:"))
        self.buttonAddPlot.setText(_translate("CustomPlots", "Add..."))
        self.buttonRemovePlot.setText(_translate("CustomPlots", "Remove"))
        self.label_2.setText(_translate("CustomPlots", "Plot function:"))
        self.buttonSave.setText(_translate("CustomPlots", "Save plots"))
        self.buttonMakePlot.setText(_translate("CustomPlots", "Make plot"))

