# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save_video.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SaveVideo(object):
    def setupUi(self, SaveVideo):
        SaveVideo.setObjectName("SaveVideo")
        SaveVideo.resize(473, 298)
        SaveVideo.setSizeGripEnabled(True)
        SaveVideo.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(SaveVideo)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label1 = QtWidgets.QLabel(SaveVideo)
        self.label1.setObjectName("label1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label1)
        self.label2 = QtWidgets.QLabel(SaveVideo)
        self.label2.setObjectName("label2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label2)
        self.comboEncoders = QtWidgets.QComboBox(SaveVideo)
        self.comboEncoders.setObjectName("comboEncoders")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboEncoders)
        self.label3 = QtWidgets.QLabel(SaveVideo)
        self.label3.setObjectName("label3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label3)
        self.spinFPS = QtWidgets.QSpinBox(SaveVideo)
        self.spinFPS.setMinimum(1)
        self.spinFPS.setMaximum(10000)
        self.spinFPS.setProperty("value", 10)
        self.spinFPS.setObjectName("spinFPS")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinFPS)
        self.label4 = QtWidgets.QLabel(SaveVideo)
        self.label4.setObjectName("label4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label4)
        self.lineeditExtraArgs = QtWidgets.QLineEdit(SaveVideo)
        self.lineeditExtraArgs.setText("")
        self.lineeditExtraArgs.setObjectName("lineeditExtraArgs")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineeditExtraArgs)
        self.label5 = QtWidgets.QLabel(SaveVideo)
        self.label5.setObjectName("label5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label5)
        self.spinBitrate = QtWidgets.QSpinBox(SaveVideo)
        self.spinBitrate.setMinimum(-1)
        self.spinBitrate.setMaximum(10000000)
        self.spinBitrate.setProperty("value", -1)
        self.spinBitrate.setObjectName("spinBitrate")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBitrate)
        self.label6 = QtWidgets.QLabel(SaveVideo)
        self.label6.setObjectName("label6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label6)
        self.lineeditCodec = QtWidgets.QLineEdit(SaveVideo)
        self.lineeditCodec.setObjectName("lineeditCodec")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineeditCodec)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineeditFilename = QtWidgets.QLineEdit(SaveVideo)
        self.lineeditFilename.setEnabled(True)
        self.lineeditFilename.setText("")
        self.lineeditFilename.setFrame(True)
        self.lineeditFilename.setObjectName("lineeditFilename")
        self.horizontalLayout_2.addWidget(self.lineeditFilename)
        self.buttonFilename = QtWidgets.QPushButton(SaveVideo)
        self.buttonFilename.setObjectName("buttonFilename")
        self.horizontalLayout_2.addWidget(self.buttonFilename)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.videoEncoderOptionsLLabel = QtWidgets.QLabel(SaveVideo)
        self.videoEncoderOptionsLLabel.setObjectName("videoEncoderOptionsLLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.videoEncoderOptionsLLabel)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(SaveVideo)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SaveVideo)
        QtCore.QMetaObject.connectSlotsByName(SaveVideo)

    def retranslateUi(self, SaveVideo):
        _translate = QtCore.QCoreApplication.translate
        SaveVideo.setWindowTitle(_translate("SaveVideo", "Export as video/sequence of images"))
        self.label1.setText(_translate("SaveVideo", "Filename"))
        self.label2.setText(_translate("SaveVideo", "Writter"))
        self.label3.setText(_translate("SaveVideo", "Framerate"))
        self.label4.setText(_translate("SaveVideo", "Extra args"))
        self.label5.setText(_translate("SaveVideo", "Bitrate"))
        self.label6.setText(_translate("SaveVideo", "Codec"))
        self.buttonFilename.setText(_translate("SaveVideo", "..."))
        self.videoEncoderOptionsLLabel.setText(_translate("SaveVideo", "Video encoder optional arguments:"))

