python whats_the_time.py console
python tutorial1.py console
python tutorial2.py console
python tutorial3.py console
python tutorial4.py console
python tutorial5.py console
python tutorial6.py console
python tutorial7.py console
python tutorial8.py console
python tutorial9.py console
python tutorial10.py console
python tutorial11.py console
python tutorial12.py console
python tutorial13.py console
python tutorial14.py console
python tutorial15.py console
python tutorial16.py console
python tutorial17.py console
python tutorial18.py console
python tutorial19.py console

python opt_tutorial1.py console
python opt_tutorial2.py console
python opt_tutorial3.py console
python opt_tutorial4.py console
python opt_tutorial5.py console
python opt_tutorial6.py console
python opt_tutorial7.py console
