# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RunExamples.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RunExamplesDialog(object):
    def setupUi(self, RunExamplesDialog):
        RunExamplesDialog.setObjectName(_fromUtf8("RunExamplesDialog"))
        RunExamplesDialog.resize(700, 400)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RunExamplesDialog.sizePolicy().hasHeightForWidth())
        RunExamplesDialog.setSizePolicy(sizePolicy)
        RunExamplesDialog.setMinimumSize(QtCore.QSize(500, 200))
        RunExamplesDialog.setMaximumSize(QtCore.QSize(10000, 100000))
        RunExamplesDialog.setSizeGripEnabled(False)
        self.horizontalLayout_3 = QtGui.QHBoxLayout(RunExamplesDialog)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(RunExamplesDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.comboBoxExample = QtGui.QComboBox(RunExamplesDialog)
        self.comboBoxExample.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxExample.sizePolicy().hasHeightForWidth())
        self.comboBoxExample.setSizePolicy(sizePolicy)
        self.comboBoxExample.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBoxExample.setObjectName(_fromUtf8("comboBoxExample"))
        self.horizontalLayout.addWidget(self.comboBoxExample)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_3 = QtGui.QLabel(RunExamplesDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.toolButtonCode = QtGui.QToolButton(RunExamplesDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonCode.sizePolicy().hasHeightForWidth())
        self.toolButtonCode.setSizePolicy(sizePolicy)
        self.toolButtonCode.setObjectName(_fromUtf8("toolButtonCode"))
        self.verticalLayout.addWidget(self.toolButtonCode)
        self.toolButtonRun = QtGui.QToolButton(RunExamplesDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonRun.sizePolicy().hasHeightForWidth())
        self.toolButtonRun.setSizePolicy(sizePolicy)
        self.toolButtonRun.setObjectName(_fromUtf8("toolButtonRun"))
        self.verticalLayout.addWidget(self.toolButtonRun)
        self.toolButtonModelReport = QtGui.QToolButton(RunExamplesDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonModelReport.sizePolicy().hasHeightForWidth())
        self.toolButtonModelReport.setSizePolicy(sizePolicy)
        self.toolButtonModelReport.setObjectName(_fromUtf8("toolButtonModelReport"))
        self.verticalLayout.addWidget(self.toolButtonModelReport)
        self.toolButtonRuntimeModelReport = QtGui.QToolButton(RunExamplesDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonRuntimeModelReport.sizePolicy().hasHeightForWidth())
        self.toolButtonRuntimeModelReport.setSizePolicy(sizePolicy)
        self.toolButtonRuntimeModelReport.setMinimumSize(QtCore.QSize(0, 0))
        self.toolButtonRuntimeModelReport.setObjectName(_fromUtf8("toolButtonRuntimeModelReport"))
        self.verticalLayout.addWidget(self.toolButtonRuntimeModelReport)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.docstringEdit = QtGui.QTextEdit(RunExamplesDialog)
        self.docstringEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.docstringEdit.sizePolicy().hasHeightForWidth())
        self.docstringEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(8)
        self.docstringEdit.setFont(font)
        self.docstringEdit.setFrameShape(QtGui.QFrame.StyledPanel)
        self.docstringEdit.setFrameShadow(QtGui.QFrame.Plain)
        self.docstringEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.docstringEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.docstringEdit.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.docstringEdit.setReadOnly(True)
        self.docstringEdit.setObjectName(_fromUtf8("docstringEdit"))
        self.verticalLayout_3.addWidget(self.docstringEdit)
        self.verticalLayout_3.setStretch(1, 2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)

        self.retranslateUi(RunExamplesDialog)
        QtCore.QMetaObject.connectSlotsByName(RunExamplesDialog)

    def retranslateUi(self, RunExamplesDialog):
        RunExamplesDialog.setWindowTitle(_translate("RunExamplesDialog", "DAE Tools Tutorials", None))
        self.label.setText(_translate("RunExamplesDialog", "Choose tutorial:", None))
        self.label_3.setText(_translate("RunExamplesDialog", "Tutorial description:", None))
        self.toolButtonCode.setText(_translate("RunExamplesDialog", "Show code...", None))
        self.toolButtonRun.setText(_translate("RunExamplesDialog", "Run...", None))
        self.toolButtonModelReport.setText(_translate("RunExamplesDialog", "Show model report ... *", None))
        self.toolButtonRuntimeModelReport.setText(_translate("RunExamplesDialog", "Show runtime model report ... *", None))

