# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RunExamples.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RunExamplesDialog(object):
    def setupUi(self, RunExamplesDialog):
        RunExamplesDialog.setObjectName("RunExamplesDialog")
        RunExamplesDialog.resize(750, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RunExamplesDialog.sizePolicy().hasHeightForWidth())
        RunExamplesDialog.setSizePolicy(sizePolicy)
        RunExamplesDialog.setMinimumSize(QtCore.QSize(500, 200))
        RunExamplesDialog.setMaximumSize(QtCore.QSize(10000, 100000))
        RunExamplesDialog.setSizeGripEnabled(False)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(RunExamplesDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(RunExamplesDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBoxExample = QtWidgets.QComboBox(RunExamplesDialog)
        self.comboBoxExample.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxExample.sizePolicy().hasHeightForWidth())
        self.comboBoxExample.setSizePolicy(sizePolicy)
        self.comboBoxExample.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBoxExample.setMaxVisibleItems(15)
        self.comboBoxExample.setObjectName("comboBoxExample")
        self.horizontalLayout.addWidget(self.comboBoxExample)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(RunExamplesDialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolButtonCode = QtWidgets.QToolButton(RunExamplesDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonCode.sizePolicy().hasHeightForWidth())
        self.toolButtonCode.setSizePolicy(sizePolicy)
        self.toolButtonCode.setObjectName("toolButtonCode")
        self.verticalLayout.addWidget(self.toolButtonCode)
        self.toolButtonRun = QtWidgets.QToolButton(RunExamplesDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonRun.sizePolicy().hasHeightForWidth())
        self.toolButtonRun.setSizePolicy(sizePolicy)
        self.toolButtonRun.setObjectName("toolButtonRun")
        self.verticalLayout.addWidget(self.toolButtonRun)
        self.toolButtonModelReport = QtWidgets.QToolButton(RunExamplesDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonModelReport.sizePolicy().hasHeightForWidth())
        self.toolButtonModelReport.setSizePolicy(sizePolicy)
        self.toolButtonModelReport.setObjectName("toolButtonModelReport")
        self.verticalLayout.addWidget(self.toolButtonModelReport)
        self.toolButtonRuntimeModelReport = QtWidgets.QToolButton(RunExamplesDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonRuntimeModelReport.sizePolicy().hasHeightForWidth())
        self.toolButtonRuntimeModelReport.setSizePolicy(sizePolicy)
        self.toolButtonRuntimeModelReport.setMinimumSize(QtCore.QSize(0, 0))
        self.toolButtonRuntimeModelReport.setObjectName("toolButtonRuntimeModelReport")
        self.verticalLayout.addWidget(self.toolButtonRuntimeModelReport)
        self.toolButtonAbout = QtWidgets.QToolButton(RunExamplesDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonAbout.sizePolicy().hasHeightForWidth())
        self.toolButtonAbout.setSizePolicy(sizePolicy)
        self.toolButtonAbout.setObjectName("toolButtonAbout")
        self.verticalLayout.addWidget(self.toolButtonAbout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.docstringWeb = QtWebKitWidgets.QWebView(RunExamplesDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.docstringWeb.sizePolicy().hasHeightForWidth())
        self.docstringWeb.setSizePolicy(sizePolicy)
        self.docstringWeb.setUrl(QtCore.QUrl("about:blank"))
        self.docstringWeb.setObjectName("docstringWeb")
        self.verticalLayout_3.addWidget(self.docstringWeb)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(RunExamplesDialog)
        QtCore.QMetaObject.connectSlotsByName(RunExamplesDialog)

    def retranslateUi(self, RunExamplesDialog):
        _translate = QtCore.QCoreApplication.translate
        RunExamplesDialog.setWindowTitle(_translate("RunExamplesDialog", "DAE Tools Tutorials"))
        self.label.setText(_translate("RunExamplesDialog", "Choose tutorial:"))
        self.label_3.setText(_translate("RunExamplesDialog", "Tutorial description:"))
        self.toolButtonCode.setText(_translate("RunExamplesDialog", "Show code ..."))
        self.toolButtonRun.setText(_translate("RunExamplesDialog", "Run ..."))
        self.toolButtonModelReport.setText(_translate("RunExamplesDialog", "Show model report ..."))
        self.toolButtonRuntimeModelReport.setText(_translate("RunExamplesDialog", "Show runtime model report ..."))
        self.toolButtonAbout.setText(_translate("RunExamplesDialog", "About DAE Tools ..."))

from PyQt5 import QtWebKitWidgets
