# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tutorial16.ui'
#
# Created: Thu May 16 02:33:44 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_InteractiveRunDialog(object):
    def setupUi(self, InteractiveRunDialog):
        InteractiveRunDialog.setObjectName(_fromUtf8("InteractiveRunDialog"))
        InteractiveRunDialog.setWindowModality(QtCore.Qt.WindowModal)
        InteractiveRunDialog.resize(729, 424)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(InteractiveRunDialog.sizePolicy().hasHeightForWidth())
        InteractiveRunDialog.setSizePolicy(sizePolicy)
        InteractiveRunDialog.setMinimumSize(QtCore.QSize(0, 0))
        InteractiveRunDialog.setMaximumSize(QtCore.QSize(1000, 1000))
        InteractiveRunDialog.setWindowTitle(_fromUtf8(""))
        InteractiveRunDialog.setSizeGripEnabled(True)
        InteractiveRunDialog.setModal(True)
        self.verticalLayout_3 = QtGui.QVBoxLayout(InteractiveRunDialog)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.controlsLayout = QtGui.QVBoxLayout()
        self.controlsLayout.setMargin(4)
        self.controlsLayout.setObjectName(_fromUtf8("controlsLayout"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(InteractiveRunDialog)
        self.label_6.setMinimumSize(QtCore.QSize(150, 0))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.powerSpinBox = QtGui.QDoubleSpinBox(InteractiveRunDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.powerSpinBox.sizePolicy().hasHeightForWidth())
        self.powerSpinBox.setSizePolicy(sizePolicy)
        self.powerSpinBox.setMinimumSize(QtCore.QSize(100, 0))
        self.powerSpinBox.setDecimals(1)
        self.powerSpinBox.setMaximum(5000.0)
        self.powerSpinBox.setSingleStep(100.0)
        self.powerSpinBox.setProperty("value", 1000.0)
        self.powerSpinBox.setObjectName(_fromUtf8("powerSpinBox"))
        self.horizontalLayout_6.addWidget(self.powerSpinBox)
        self.label_7 = QtGui.QLabel(InteractiveRunDialog)
        self.label_7.setMinimumSize(QtCore.QSize(20, 0))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.controlsLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(InteractiveRunDialog)
        self.label_3.setMinimumSize(QtCore.QSize(150, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.reportingIntervalSpinBox = QtGui.QDoubleSpinBox(InteractiveRunDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reportingIntervalSpinBox.sizePolicy().hasHeightForWidth())
        self.reportingIntervalSpinBox.setSizePolicy(sizePolicy)
        self.reportingIntervalSpinBox.setMinimumSize(QtCore.QSize(100, 0))
        self.reportingIntervalSpinBox.setMaximum(1000.0)
        self.reportingIntervalSpinBox.setObjectName(_fromUtf8("reportingIntervalSpinBox"))
        self.horizontalLayout_5.addWidget(self.reportingIntervalSpinBox)
        self.label_4 = QtGui.QLabel(InteractiveRunDialog)
        self.label_4.setMinimumSize(QtCore.QSize(20, 0))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.controlsLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(InteractiveRunDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(150, 0))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.intervalSpinBox = QtGui.QDoubleSpinBox(InteractiveRunDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intervalSpinBox.sizePolicy().hasHeightForWidth())
        self.intervalSpinBox.setSizePolicy(sizePolicy)
        self.intervalSpinBox.setMinimumSize(QtCore.QSize(100, 0))
        self.intervalSpinBox.setMinimum(0.1)
        self.intervalSpinBox.setMaximum(10000.0)
        self.intervalSpinBox.setProperty("value", 100.0)
        self.intervalSpinBox.setObjectName(_fromUtf8("intervalSpinBox"))
        self.horizontalLayout.addWidget(self.intervalSpinBox)
        self.label_5 = QtGui.QLabel(InteractiveRunDialog)
        self.label_5.setMinimumSize(QtCore.QSize(20, 0))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.controlsLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setContentsMargins(0, -1, -1, 0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(InteractiveRunDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.currentTimeEdit = QtGui.QLineEdit(InteractiveRunDialog)
        self.currentTimeEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentTimeEdit.sizePolicy().hasHeightForWidth())
        self.currentTimeEdit.setSizePolicy(sizePolicy)
        self.currentTimeEdit.setMinimumSize(QtCore.QSize(40, 0))
        self.currentTimeEdit.setFrame(False)
        self.currentTimeEdit.setObjectName(_fromUtf8("currentTimeEdit"))
        self.horizontalLayout_4.addWidget(self.currentTimeEdit)
        self.controlsLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_3.setMargin(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.runButton = QtGui.QPushButton(InteractiveRunDialog)
        self.runButton.setMinimumSize(QtCore.QSize(30, 0))
        self.runButton.setBaseSize(QtCore.QSize(40, 0))
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.horizontalLayout_3.addWidget(self.runButton)
        self.controlsLayout.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.controlsLayout.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.controlsLayout)
        self.plotLayout = QtGui.QVBoxLayout()
        self.plotLayout.setMargin(0)
        self.plotLayout.setObjectName(_fromUtf8("plotLayout"))
        self.frame = QtGui.QFrame(InteractiveRunDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(510, 410))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.plotLayout.addWidget(self.frame)
        self.horizontalLayout_2.addLayout(self.plotLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(InteractiveRunDialog)
        QtCore.QMetaObject.connectSlotsByName(InteractiveRunDialog)

    def retranslateUi(self, InteractiveRunDialog):
        self.label_6.setText(QtGui.QApplication.translate("InteractiveRunDialog", "Input power (Qin):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("InteractiveRunDialog", "W", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("InteractiveRunDialog", "Reporting Interval:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("InteractiveRunDialog", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("InteractiveRunDialog", "Integrate for:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("InteractiveRunDialog", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("InteractiveRunDialog", "Current time:", None, QtGui.QApplication.UnicodeUTF8))
        self.currentTimeEdit.setText(QtGui.QApplication.translate("InteractiveRunDialog", "0.0 s", None, QtGui.QApplication.UnicodeUTF8))
        self.runButton.setText(QtGui.QApplication.translate("InteractiveRunDialog", "Run", None, QtGui.QApplication.UnicodeUTF8))

