# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'activity.ui'
#
# Created: Sun Feb 14 18:54:07 2010
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Activity(object):
    def setupUi(self, Activity):
        Activity.setObjectName("Activity")
        Activity.resize(550, 400)
        Activity.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Activity.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(Activity)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setMargin(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabLogInformation = QtGui.QTabWidget(self.centralwidget)
        self.tabLogInformation.setMinimumSize(QtCore.QSize(400, 200))
        self.tabLogInformation.setTabPosition(QtGui.QTabWidget.South)
        self.tabLogInformation.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabLogInformation.setElideMode(QtCore.Qt.ElideNone)
        self.tabLogInformation.setMovable(True)
        self.tabLogInformation.setObjectName("tabLogInformation")
        self.tabLog = QtGui.QWidget()
        self.tabLog.setObjectName("tabLog")
        self.horizontalLayout = QtGui.QHBoxLayout(self.tabLog)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEditLog = QtGui.QTextEdit(self.tabLog)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        self.textEditLog.setFont(font)
        self.textEditLog.setFrameShape(QtGui.QFrame.NoFrame)
        self.textEditLog.setFrameShadow(QtGui.QFrame.Plain)
        self.textEditLog.setLineWidth(0)
        self.textEditLog.setReadOnly(True)
        self.textEditLog.setObjectName("textEditLog")
        self.horizontalLayout.addWidget(self.textEditLog)
        self.tabLogInformation.addTab(self.tabLog, "")
        self.tabCout = QtGui.QWidget()
        self.tabCout.setObjectName("tabCout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tabCout)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEditCout = QtGui.QTextEdit(self.tabCout)
        self.textEditCout.setFrameShape(QtGui.QFrame.NoFrame)
        self.textEditCout.setFrameShadow(QtGui.QFrame.Plain)
        self.textEditCout.setLineWidth(0)
        self.textEditCout.setReadOnly(True)
        self.textEditCout.setObjectName("textEditCout")
        self.horizontalLayout_2.addWidget(self.textEditCout)
        self.tabLogInformation.addTab(self.tabCout, "")
        self.tabCerr = QtGui.QWidget()
        self.tabCerr.setObjectName("tabCerr")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tabCerr)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textEditCerr = QtGui.QTextEdit(self.tabCerr)
        self.textEditCerr.setFrameShape(QtGui.QFrame.NoFrame)
        self.textEditCerr.setFrameShadow(QtGui.QFrame.Plain)
        self.textEditCerr.setLineWidth(0)
        self.textEditCerr.setReadOnly(True)
        self.textEditCerr.setObjectName("textEditCerr")
        self.horizontalLayout_3.addWidget(self.textEditCerr)
        self.tabLogInformation.addTab(self.tabCerr, "")
        self.tabClog = QtGui.QWidget()
        self.tabClog.setObjectName("tabClog")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tabClog)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.textEditClog = QtGui.QTextEdit(self.tabClog)
        self.textEditClog.setFrameShape(QtGui.QFrame.NoFrame)
        self.textEditClog.setFrameShadow(QtGui.QFrame.Plain)
        self.textEditClog.setLineWidth(0)
        self.textEditClog.setReadOnly(True)
        self.textEditClog.setObjectName("textEditClog")
        self.horizontalLayout_4.addWidget(self.textEditClog)
        self.tabLogInformation.addTab(self.tabClog, "")
        self.verticalLayout_3.addWidget(self.tabLogInformation)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        Activity.setCentralWidget(self.centralwidget)
        self.toolBar = QtGui.QToolBar(Activity)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(24, 24))
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        Activity.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionPause = QtGui.QAction(Activity)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("images/play.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.actionPause.setIcon(icon1)
        self.actionPause.setObjectName("actionPause")
        self.actionStop = QtGui.QAction(Activity)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/abort.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon2)
        self.actionStop.setObjectName("actionStop")
        self.actionRun = QtGui.QAction(Activity)
        self.actionRun.setIcon(icon)
        self.actionRun.setObjectName("actionRun")
        self.toolBar.addAction(self.actionPause)
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addAction(self.actionStop)

        self.retranslateUi(Activity)
        self.tabLogInformation.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Activity)

    def retranslateUi(self, Activity):
        Activity.setWindowTitle(QtGui.QApplication.translate("Activity", "Activity execution", None, QtGui.QApplication.UnicodeUTF8))
        self.textEditLog.setHtml(QtGui.QApplication.translate("Activity", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Courier New\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'DejaVu Sans\';\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabLogInformation.setTabText(self.tabLogInformation.indexOf(self.tabLog), QtGui.QApplication.translate("Activity", "DAE Log", None, QtGui.QApplication.UnicodeUTF8))
        self.tabLogInformation.setTabText(self.tabLogInformation.indexOf(self.tabCout), QtGui.QApplication.translate("Activity", "cout", None, QtGui.QApplication.UnicodeUTF8))
        self.tabLogInformation.setTabText(self.tabLogInformation.indexOf(self.tabCerr), QtGui.QApplication.translate("Activity", "cerr", None, QtGui.QApplication.UnicodeUTF8))
        self.tabLogInformation.setTabText(self.tabLogInformation.indexOf(self.tabClog), QtGui.QApplication.translate("Activity", "clog", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("Activity", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPause.setText(QtGui.QApplication.translate("Activity", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop.setText(QtGui.QApplication.translate("Activity", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun.setText(QtGui.QApplication.translate("Activity", "Run", None, QtGui.QApplication.UnicodeUTF8))

#import daecreator_rc
