# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor_domain_array.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EditorArrayDomain(object):
    def setupUi(self, EditorArrayDomain):
        EditorArrayDomain.setObjectName("EditorArrayDomain")
        EditorArrayDomain.resize(250, 243)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EditorArrayDomain.sizePolicy().hasHeightForWidth())
        EditorArrayDomain.setSizePolicy(sizePolicy)
        EditorArrayDomain.setMinimumSize(QtCore.QSize(250, 200))
        EditorArrayDomain.setWindowTitle("")
        EditorArrayDomain.setFrameShape(QtWidgets.QFrame.NoFrame)
        EditorArrayDomain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout = QtWidgets.QVBoxLayout(EditorArrayDomain)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(EditorArrayDomain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.numberOfPointsEdit = QtWidgets.QLineEdit(EditorArrayDomain)
        self.numberOfPointsEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numberOfPointsEdit.sizePolicy().hasHeightForWidth())
        self.numberOfPointsEdit.setSizePolicy(sizePolicy)
        self.numberOfPointsEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.numberOfPointsEdit.setObjectName("numberOfPointsEdit")
        self.horizontalLayout_4.addWidget(self.numberOfPointsEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(EditorArrayDomain)
        self.label_4.setMinimumSize(QtCore.QSize(80, 0))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.descriptionEdit = QtWidgets.QTextEdit(EditorArrayDomain)
        self.descriptionEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descriptionEdit.sizePolicy().hasHeightForWidth())
        self.descriptionEdit.setSizePolicy(sizePolicy)
        self.descriptionEdit.setMinimumSize(QtCore.QSize(100, 50))
        self.descriptionEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.descriptionEdit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.descriptionEdit.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.descriptionEdit.setReadOnly(True)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.verticalLayout_2.addWidget(self.descriptionEdit)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.updateButton = QtWidgets.QPushButton(EditorArrayDomain)
        self.updateButton.setEnabled(False)
        self.updateButton.setAutoDefault(True)
        self.updateButton.setDefault(True)
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout_2.addWidget(self.updateButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(EditorArrayDomain)
        QtCore.QMetaObject.connectSlotsByName(EditorArrayDomain)

    def retranslateUi(self, EditorArrayDomain):
        _translate = QtCore.QCoreApplication.translate
        self.label_3.setText(_translate("EditorArrayDomain", "Number of Points"))
        self.numberOfPointsEdit.setToolTip(_translate("EditorArrayDomain", "<html><head/><body>Insert the number of points in the domain (integer).</body></html>"))
        self.label_4.setText(_translate("EditorArrayDomain", "Description"))
        self.descriptionEdit.setToolTip(_translate("EditorArrayDomain", "<html><head/><body><p>Description of the object.</p></body></html>"))
        self.updateButton.setToolTip(_translate("EditorArrayDomain", "<html><head/><body><p>Update the number of points.</p></body></html>"))
        self.updateButton.setText(_translate("EditorArrayDomain", "Update"))

