#!/bin/sh

export TRILINOS_HOME=~/dae-tools/trunk/trilinos-10.4.0-Source
EXTRA_ARGS=$@

cmake \
  -DCMAKE_BUILD_TYPE:STRING=RELEASE \
  -DBUILD_SHARED_LIBS:BOOL=ON \
  -DTrilinos_ENABLE_Amesos:BOOL=ON \
  -DTrilinos_ENABLE_Epetra:BOOL=ON \
  -DAmesos_ENABLE_SuperLU:BOOL=ON \
  -DTPL_SuperLU_INCLUDE_DIRS:FILEPATH=/usr/include/superlu \
  -DTPL_ENABLE_UMFPACK:BOOL=ON \
  -DTPL_UMFPACK_INCLUDE_DIRS:FILEPATH=/usr/include/suitesparse \
  -DTPL_ENABLE_MPI:BOOL=OFF \
  -DDART_TESTING_TIMEOUT:STRING=600 \
  -DCMAKE_INSTALL_PREFIX:PATH=. \
  -DCMAKE_SHARED_LINKER_FLAGS:STRING="-s" \
  $EXTRA_ARGS \
  ${TRILINOS_HOME}
