#!/bin/sh

export TRILINOS_HOME=~/Data/daetools/trunk/trilinos
EXTRA_ARGS=$@

cmake \
  -DCMAKE_BUILD_TYPE:STRING=RELEASE \
  -DBUILD_SHARED_LIBS:BOOL=OFF \
  -DTrilinos_ENABLE_Amesos:BOOL=ON \
  -DTrilinos_ENABLE_Epetra:BOOL=ON \
  -DAmesos_ENABLE_SuperLU:BOOL=ON \
  -DTPL_SuperLU_INCLUDE_DIRS:FILEPATH=/usr/include/superlu \
  -DTPL_ENABLE_UMFPACK:BOOL=ON \
  -DTPL_UMFPACK_INCLUDE_DIRS:FILEPATH=/usr/include/suitesparse \
  -DTPL_ENABLE_MPI:BOOL=OFF \
  -DDART_TESTING_TIMEOUT:STRING=600 \
  -DCMAKE_INSTALL_PREFIX:PATH=. \
  -DCMAKE_CXX_FLAGS:STRING="-DNDEBUG -fPIC" \
  -DCMAKE_C_FLAGS:STRING="-DNDEBUG -fPIC" \
  -DCMAKE_Fortran_FLAGS:STRING="-DNDEBUG -fPIC" \
  $EXTRA_ARGS \
  ${TRILINOS_HOME}
 