# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor_state_transition.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EditorStateTransition(object):
    def setupUi(self, EditorStateTransition):
        EditorStateTransition.setObjectName("EditorStateTransition")
        EditorStateTransition.resize(250, 247)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EditorStateTransition.sizePolicy().hasHeightForWidth())
        EditorStateTransition.setSizePolicy(sizePolicy)
        EditorStateTransition.setMinimumSize(QtCore.QSize(250, 200))
        EditorStateTransition.setWindowTitle("")
        EditorStateTransition.setFrameShape(QtWidgets.QFrame.NoFrame)
        EditorStateTransition.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout = QtWidgets.QVBoxLayout(EditorStateTransition)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(EditorStateTransition)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.activeStateComboBox = QtWidgets.QComboBox(EditorStateTransition)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activeStateComboBox.sizePolicy().hasHeightForWidth())
        self.activeStateComboBox.setSizePolicy(sizePolicy)
        self.activeStateComboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.activeStateComboBox.setObjectName("activeStateComboBox")
        self.horizontalLayout.addWidget(self.activeStateComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(EditorStateTransition)
        self.label_5.setMinimumSize(QtCore.QSize(80, 0))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.descriptionEdit = QtWidgets.QTextEdit(EditorStateTransition)
        self.descriptionEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descriptionEdit.sizePolicy().hasHeightForWidth())
        self.descriptionEdit.setSizePolicy(sizePolicy)
        self.descriptionEdit.setMinimumSize(QtCore.QSize(100, 50))
        self.descriptionEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.descriptionEdit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.descriptionEdit.setReadOnly(True)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.verticalLayout_4.addWidget(self.descriptionEdit)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.updateButton = QtWidgets.QPushButton(EditorStateTransition)
        self.updateButton.setAutoDefault(True)
        self.updateButton.setDefault(True)
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout_2.addWidget(self.updateButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(EditorStateTransition)
        QtCore.QMetaObject.connectSlotsByName(EditorStateTransition)

    def retranslateUi(self, EditorStateTransition):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("EditorStateTransition", "Active State"))
        self.activeStateComboBox.setToolTip(_translate("EditorStateTransition", "<html><head/><body><p>Select the active state from the list of available states (string).</p></body></html>"))
        self.label_5.setText(_translate("EditorStateTransition", "Description"))
        self.descriptionEdit.setToolTip(_translate("EditorStateTransition", "<html><head/><body><p>Description of the object.</p></body></html>"))
        self.updateButton.setToolTip(_translate("EditorStateTransition", "<html><head/><body><p>Update the active state.</p></body></html>"))
        self.updateButton.setText(_translate("EditorStateTransition", "Update"))

