# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulation_explorer.ui'
#
# Created: Tue Oct 15 03:47:20 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SimulationExplorer(object):
    def setupUi(self, SimulationExplorer):
        SimulationExplorer.setObjectName(_fromUtf8("SimulationExplorer"))
        SimulationExplorer.setWindowModality(QtCore.Qt.WindowModal)
        SimulationExplorer.resize(760, 550)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SimulationExplorer.sizePolicy().hasHeightForWidth())
        SimulationExplorer.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtGui.QVBoxLayout(SimulationExplorer)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(SimulationExplorer)
        self.tabWidget.setMinimumSize(QtCore.QSize(250, 0))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_Runtume = QtGui.QWidget()
        self.tab_Runtume.setObjectName(_fromUtf8("tab_Runtume"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_Runtume)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.testNameLabel = QtGui.QLabel(self.tab_Runtume)
        self.testNameLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.testNameLabel.setObjectName(_fromUtf8("testNameLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.testNameLabel)
        self.simulationNameEdit = QtGui.QLineEdit(self.tab_Runtume)
        self.simulationNameEdit.setEnabled(True)
        self.simulationNameEdit.setText(_fromUtf8(""))
        self.simulationNameEdit.setObjectName(_fromUtf8("simulationNameEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.simulationNameEdit)
        self.timeHorizonLabel = QtGui.QLabel(self.tab_Runtume)
        self.timeHorizonLabel.setObjectName(_fromUtf8("timeHorizonLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.timeHorizonLabel)
        self.timeHorizonEdit = QtGui.QLineEdit(self.tab_Runtume)
        self.timeHorizonEdit.setInputMask(_fromUtf8(""))
        self.timeHorizonEdit.setObjectName(_fromUtf8("timeHorizonEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.timeHorizonEdit)
        self.reportingIntervalLabel = QtGui.QLabel(self.tab_Runtume)
        self.reportingIntervalLabel.setObjectName(_fromUtf8("reportingIntervalLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.reportingIntervalLabel)
        self.reportingIntervalEdit = QtGui.QLineEdit(self.tab_Runtume)
        self.reportingIntervalEdit.setObjectName(_fromUtf8("reportingIntervalEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.reportingIntervalEdit)
        self.relativeToleranceLabel = QtGui.QLabel(self.tab_Runtume)
        self.relativeToleranceLabel.setObjectName(_fromUtf8("relativeToleranceLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.relativeToleranceLabel)
        self.relativeToleranceEdit = QtGui.QLineEdit(self.tab_Runtume)
        self.relativeToleranceEdit.setObjectName(_fromUtf8("relativeToleranceEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.relativeToleranceEdit)
        self.daesolverLabel = QtGui.QLabel(self.tab_Runtume)
        self.daesolverLabel.setObjectName(_fromUtf8("daesolverLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.daesolverLabel)
        self.daesolverComboBox = QtGui.QComboBox(self.tab_Runtume)
        self.daesolverComboBox.setObjectName(_fromUtf8("daesolverComboBox"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.daesolverComboBox)
        self.lasolverLabel = QtGui.QLabel(self.tab_Runtume)
        self.lasolverLabel.setObjectName(_fromUtf8("lasolverLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.lasolverLabel)
        self.lasolverComboBox = QtGui.QComboBox(self.tab_Runtume)
        self.lasolverComboBox.setObjectName(_fromUtf8("lasolverComboBox"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.lasolverComboBox)
        self.dataReporterLabel = QtGui.QLabel(self.tab_Runtume)
        self.dataReporterLabel.setObjectName(_fromUtf8("dataReporterLabel"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.dataReporterLabel)
        self.datareporterComboBox = QtGui.QComboBox(self.tab_Runtume)
        self.datareporterComboBox.setObjectName(_fromUtf8("datareporterComboBox"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.datareporterComboBox)
        self.logLabel = QtGui.QLabel(self.tab_Runtume)
        self.logLabel.setObjectName(_fromUtf8("logLabel"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.logLabel)
        self.logComboBox = QtGui.QComboBox(self.tab_Runtume)
        self.logComboBox.setObjectName(_fromUtf8("logComboBox"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.logComboBox)
        self.minlpSolverLabel = QtGui.QLabel(self.tab_Runtume)
        self.minlpSolverLabel.setObjectName(_fromUtf8("minlpSolverLabel"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.minlpSolverLabel)
        self.minlpsolverComboBox = QtGui.QComboBox(self.tab_Runtume)
        self.minlpsolverComboBox.setObjectName(_fromUtf8("minlpsolverComboBox"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.minlpsolverComboBox)
        self.verticalLayout_6.addLayout(self.formLayout)
        self.tabWidget.addTab(self.tab_Runtume, _fromUtf8(""))
        self.tab_Domains = QtGui.QWidget()
        self.tab_Domains.setObjectName(_fromUtf8("tab_Domains"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_Domains)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.treeDomains = QtGui.QTreeWidget(self.tab_Domains)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeDomains.sizePolicy().hasHeightForWidth())
        self.treeDomains.setSizePolicy(sizePolicy)
        self.treeDomains.setMinimumSize(QtCore.QSize(400, 200))
        self.treeDomains.setAlternatingRowColors(True)
        self.treeDomains.setObjectName(_fromUtf8("treeDomains"))
        self.treeDomains.header().setDefaultSectionSize(300)
        self.treeDomains.header().setMinimumSectionSize(100)
        self.horizontalLayout.addWidget(self.treeDomains)
        self.frameDomains = QtGui.QFrame(self.tab_Domains)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frameDomains.sizePolicy().hasHeightForWidth())
        self.frameDomains.setSizePolicy(sizePolicy)
        self.frameDomains.setMinimumSize(QtCore.QSize(250, 200))
        self.frameDomains.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameDomains.setFrameShadow(QtGui.QFrame.Raised)
        self.frameDomains.setObjectName(_fromUtf8("frameDomains"))
        self.horizontalLayout.addWidget(self.frameDomains)
        self.tabWidget.addTab(self.tab_Domains, _fromUtf8(""))
        self.tab_Parameters = QtGui.QWidget()
        self.tab_Parameters.setObjectName(_fromUtf8("tab_Parameters"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_Parameters)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.treeParameters = QtGui.QTreeWidget(self.tab_Parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeParameters.sizePolicy().hasHeightForWidth())
        self.treeParameters.setSizePolicy(sizePolicy)
        self.treeParameters.setMinimumSize(QtCore.QSize(100, 200))
        self.treeParameters.setStyleSheet(_fromUtf8(" /*\n"
"QTreeWidget::branch:has-siblings:!adjoins-item {\n"
"     border-image: url(images/vline.png) 0;\n"
" }\n"
"\n"
" QTreeWidget::branch:has-siblings:adjoins-item {\n"
"     border-image: url(images/branch-more.png) 0;\n"
" }\n"
"\n"
" QTreeWidget::branch:!has-children:!has-siblings:adjoins-item {\n"
"     border-image: url(images/branch-end.png) 0;\n"
" }\n"
"\n"
" QTreeWidget::branch:has-children:!has-siblings:closed,\n"
" QTreeWidget::branch:closed:has-children:has-siblings {\n"
"         border-image: none;\n"
"         image: url(images/branch-closed.png);\n"
" }\n"
"\n"
" QTreeWidget::branch:open:has-children:!has-siblings,\n"
" QTreeWidget::branch:open:has-children:has-siblings  {\n"
"         border-image: none;\n"
"         image: url(images/branch-open.png);\n"
" }\n"
"*/\n"
""))
        self.treeParameters.setAlternatingRowColors(True)
        self.treeParameters.setObjectName(_fromUtf8("treeParameters"))
        self.treeParameters.header().setDefaultSectionSize(300)
        self.treeParameters.header().setMinimumSectionSize(100)
        self.horizontalLayout_3.addWidget(self.treeParameters)
        self.frameParameters = QtGui.QFrame(self.tab_Parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frameParameters.sizePolicy().hasHeightForWidth())
        self.frameParameters.setSizePolicy(sizePolicy)
        self.frameParameters.setMinimumSize(QtCore.QSize(250, 200))
        self.frameParameters.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameParameters.setFrameShadow(QtGui.QFrame.Raised)
        self.frameParameters.setObjectName(_fromUtf8("frameParameters"))
        self.horizontalLayout_3.addWidget(self.frameParameters)
        self.tabWidget.addTab(self.tab_Parameters, _fromUtf8(""))
        self.tab_InitialConditions = QtGui.QWidget()
        self.tab_InitialConditions.setObjectName(_fromUtf8("tab_InitialConditions"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_InitialConditions)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.quazySteadyStateCheckBox = QtGui.QCheckBox(self.tab_InitialConditions)
        self.quazySteadyStateCheckBox.setEnabled(False)
        self.quazySteadyStateCheckBox.setObjectName(_fromUtf8("quazySteadyStateCheckBox"))
        self.horizontalLayout_4.addWidget(self.quazySteadyStateCheckBox)
        self.initialConditionsLabel = QtGui.QLabel(self.tab_InitialConditions)
        self.initialConditionsLabel.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.initialConditionsLabel.sizePolicy().hasHeightForWidth())
        self.initialConditionsLabel.setSizePolicy(sizePolicy)
        self.initialConditionsLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.initialConditionsLabel.setObjectName(_fromUtf8("initialConditionsLabel"))
        self.horizontalLayout_4.addWidget(self.initialConditionsLabel)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.treeInitialConditions = QtGui.QTreeWidget(self.tab_InitialConditions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeInitialConditions.sizePolicy().hasHeightForWidth())
        self.treeInitialConditions.setSizePolicy(sizePolicy)
        self.treeInitialConditions.setMinimumSize(QtCore.QSize(400, 200))
        self.treeInitialConditions.setAlternatingRowColors(True)
        self.treeInitialConditions.setObjectName(_fromUtf8("treeInitialConditions"))
        self.treeInitialConditions.header().setDefaultSectionSize(300)
        self.treeInitialConditions.header().setMinimumSectionSize(100)
        self.horizontalLayout_7.addWidget(self.treeInitialConditions)
        self.frameInitialConditions = QtGui.QFrame(self.tab_InitialConditions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frameInitialConditions.sizePolicy().hasHeightForWidth())
        self.frameInitialConditions.setSizePolicy(sizePolicy)
        self.frameInitialConditions.setMinimumSize(QtCore.QSize(250, 200))
        self.frameInitialConditions.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameInitialConditions.setFrameShadow(QtGui.QFrame.Raised)
        self.frameInitialConditions.setObjectName(_fromUtf8("frameInitialConditions"))
        self.horizontalLayout_7.addWidget(self.frameInitialConditions)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab_InitialConditions, _fromUtf8(""))
        self.tab_DOFs = QtGui.QWidget()
        self.tab_DOFs.setObjectName(_fromUtf8("tab_DOFs"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tab_DOFs)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.treeDOFs = QtGui.QTreeWidget(self.tab_DOFs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeDOFs.sizePolicy().hasHeightForWidth())
        self.treeDOFs.setSizePolicy(sizePolicy)
        self.treeDOFs.setMinimumSize(QtCore.QSize(400, 200))
        self.treeDOFs.setAlternatingRowColors(True)
        self.treeDOFs.setObjectName(_fromUtf8("treeDOFs"))
        self.treeDOFs.header().setDefaultSectionSize(300)
        self.treeDOFs.header().setMinimumSectionSize(100)
        self.horizontalLayout_6.addWidget(self.treeDOFs)
        self.frameDOFs = QtGui.QFrame(self.tab_DOFs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frameDOFs.sizePolicy().hasHeightForWidth())
        self.frameDOFs.setSizePolicy(sizePolicy)
        self.frameDOFs.setMinimumSize(QtCore.QSize(250, 200))
        self.frameDOFs.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameDOFs.setFrameShadow(QtGui.QFrame.Raised)
        self.frameDOFs.setObjectName(_fromUtf8("frameDOFs"))
        self.horizontalLayout_6.addWidget(self.frameDOFs)
        self.tabWidget.addTab(self.tab_DOFs, _fromUtf8(""))
        self.tab_StateTransitions = QtGui.QWidget()
        self.tab_StateTransitions.setObjectName(_fromUtf8("tab_StateTransitions"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tab_StateTransitions)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.treeSTNs = QtGui.QTreeWidget(self.tab_StateTransitions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeSTNs.sizePolicy().hasHeightForWidth())
        self.treeSTNs.setSizePolicy(sizePolicy)
        self.treeSTNs.setMinimumSize(QtCore.QSize(400, 200))
        self.treeSTNs.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeSTNs.setAlternatingRowColors(True)
        self.treeSTNs.setColumnCount(1)
        self.treeSTNs.setObjectName(_fromUtf8("treeSTNs"))
        self.treeSTNs.header().setVisible(False)
        self.treeSTNs.header().setDefaultSectionSize(300)
        self.treeSTNs.header().setMinimumSectionSize(100)
        self.horizontalLayout_5.addWidget(self.treeSTNs)
        self.tabWidget.addTab(self.tab_StateTransitions, _fromUtf8(""))
        self.tab_Results = QtGui.QWidget()
        self.tab_Results.setObjectName(_fromUtf8("tab_Results"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_Results)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.treeOutputVariables = QtGui.QTreeWidget(self.tab_Results)
        self.treeOutputVariables.setAlternatingRowColors(True)
        self.treeOutputVariables.setColumnCount(1)
        self.treeOutputVariables.setObjectName(_fromUtf8("treeOutputVariables"))
        self.treeOutputVariables.header().setVisible(False)
        self.treeOutputVariables.header().setDefaultSectionSize(300)
        self.treeOutputVariables.header().setMinimumSectionSize(100)
        self.verticalLayout_8.addWidget(self.treeOutputVariables)
        self.tabWidget.addTab(self.tab_Results, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.buttonCancel = QtGui.QPushButton(SimulationExplorer)
        self.buttonCancel.setMinimumSize(QtCore.QSize(100, 0))
        self.buttonCancel.setAutoDefault(False)
        self.buttonCancel.setDefault(False)
        self.buttonCancel.setObjectName(_fromUtf8("buttonCancel"))
        self.horizontalLayout_2.addWidget(self.buttonCancel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.buttonSaveRuntimeSettingsAsJSON = QtGui.QPushButton(SimulationExplorer)
        self.buttonSaveRuntimeSettingsAsJSON.setAutoDefault(False)
        self.buttonSaveRuntimeSettingsAsJSON.setObjectName(_fromUtf8("buttonSaveRuntimeSettingsAsJSON"))
        self.horizontalLayout_2.addWidget(self.buttonSaveRuntimeSettingsAsJSON)
        self.buttonGenerateCode = QtGui.QPushButton(SimulationExplorer)
        self.buttonGenerateCode.setAutoDefault(False)
        self.buttonGenerateCode.setObjectName(_fromUtf8("buttonGenerateCode"))
        self.horizontalLayout_2.addWidget(self.buttonGenerateCode)
        self.buttonUpdateSimulationAndClose = QtGui.QPushButton(SimulationExplorer)
        self.buttonUpdateSimulationAndClose.setAutoDefault(False)
        self.buttonUpdateSimulationAndClose.setObjectName(_fromUtf8("buttonUpdateSimulationAndClose"))
        self.horizontalLayout_2.addWidget(self.buttonUpdateSimulationAndClose)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(SimulationExplorer)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SimulationExplorer)

    def retranslateUi(self, SimulationExplorer):
        SimulationExplorer.setWindowTitle(QtGui.QApplication.translate("SimulationExplorer", "Simulation Explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.testNameLabel.setText(QtGui.QApplication.translate("SimulationExplorer", "Simulation name", None, QtGui.QApplication.UnicodeUTF8))
        self.timeHorizonLabel.setText(QtGui.QApplication.translate("SimulationExplorer", "Time horizon, s", None, QtGui.QApplication.UnicodeUTF8))
        self.timeHorizonEdit.setText(QtGui.QApplication.translate("SimulationExplorer", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.reportingIntervalLabel.setText(QtGui.QApplication.translate("SimulationExplorer", "Reporting interval, s", None, QtGui.QApplication.UnicodeUTF8))
        self.reportingIntervalEdit.setText(QtGui.QApplication.translate("SimulationExplorer", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.relativeToleranceLabel.setText(QtGui.QApplication.translate("SimulationExplorer", "Relative Tolerance", None, QtGui.QApplication.UnicodeUTF8))
        self.daesolverLabel.setText(QtGui.QApplication.translate("SimulationExplorer", "DAE Solver", None, QtGui.QApplication.UnicodeUTF8))
        self.lasolverLabel.setText(QtGui.QApplication.translate("SimulationExplorer", "LA Solver", None, QtGui.QApplication.UnicodeUTF8))
        self.dataReporterLabel.setText(QtGui.QApplication.translate("SimulationExplorer", "Data Reporter", None, QtGui.QApplication.UnicodeUTF8))
        self.logLabel.setText(QtGui.QApplication.translate("SimulationExplorer", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.minlpSolverLabel.setText(QtGui.QApplication.translate("SimulationExplorer", "(MI)NLP Solver", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Runtume), QtGui.QApplication.translate("SimulationExplorer", "Runtime", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_Runtume), QtGui.QApplication.translate("SimulationExplorer", "<html><head/><body><p>Set the runtime data.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.treeDomains.headerItem().setText(0, QtGui.QApplication.translate("SimulationExplorer", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.treeDomains.headerItem().setText(1, QtGui.QApplication.translate("SimulationExplorer", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Domains), QtGui.QApplication.translate("SimulationExplorer", "Domains", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_Domains), QtGui.QApplication.translate("SimulationExplorer", "<html><head/><body><p>Set the data related to domains.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.treeParameters.headerItem().setText(0, QtGui.QApplication.translate("SimulationExplorer", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.treeParameters.headerItem().setText(1, QtGui.QApplication.translate("SimulationExplorer", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Parameters), QtGui.QApplication.translate("SimulationExplorer", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_Parameters), QtGui.QApplication.translate("SimulationExplorer", "<html><head/><body><p>Set the data related to parameters.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.initialConditionsLabel.setText(QtGui.QApplication.translate("SimulationExplorer", "Quazy Steady State InitialConditions", None, QtGui.QApplication.UnicodeUTF8))
        self.treeInitialConditions.headerItem().setText(0, QtGui.QApplication.translate("SimulationExplorer", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.treeInitialConditions.headerItem().setText(1, QtGui.QApplication.translate("SimulationExplorer", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_InitialConditions), QtGui.QApplication.translate("SimulationExplorer", "InitialConditions", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_InitialConditions), QtGui.QApplication.translate("SimulationExplorer", "<html><head/><body><p>Set the initial conditions for differential variables.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.treeDOFs.headerItem().setText(0, QtGui.QApplication.translate("SimulationExplorer", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.treeDOFs.headerItem().setText(1, QtGui.QApplication.translate("SimulationExplorer", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_DOFs), QtGui.QApplication.translate("SimulationExplorer", "DoFs", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_DOFs), QtGui.QApplication.translate("SimulationExplorer", "<html><head/><body><p>Set the values of assigned variables (Degrees of Freedom).</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.treeSTNs.headerItem().setText(0, QtGui.QApplication.translate("SimulationExplorer", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_StateTransitions), QtGui.QApplication.translate("SimulationExplorer", "STNs", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_StateTransitions), QtGui.QApplication.translate("SimulationExplorer", "<html><head/><body><p>Set the data related to State Transition Networks.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.treeOutputVariables.headerItem().setText(0, QtGui.QApplication.translate("SimulationExplorer", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Results), QtGui.QApplication.translate("SimulationExplorer", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_Results), QtGui.QApplication.translate("SimulationExplorer", "<html><head/><body><p>Select variables to appear in the output.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonCancel.setToolTip(QtGui.QApplication.translate("SimulationExplorer", "<html><head/><body><p>Close this form without updating the simulation.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonCancel.setText(QtGui.QApplication.translate("SimulationExplorer", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSaveRuntimeSettingsAsJSON.setToolTip(QtGui.QApplication.translate("SimulationExplorer", "<html><head/><body><p>Save runtime settings in JSON format to the specified file.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSaveRuntimeSettingsAsJSON.setText(QtGui.QApplication.translate("SimulationExplorer", "Save Settings as JSON...", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonGenerateCode.setToolTip(QtGui.QApplication.translate("SimulationExplorer", "<html><head/><body><p>Generate the code for a selected language (ANSI C, Modelica, FMI).</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonGenerateCode.setText(QtGui.QApplication.translate("SimulationExplorer", "Generate code...", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonUpdateSimulationAndClose.setToolTip(QtGui.QApplication.translate("SimulationExplorer", "<html><head/><body><p>Update the simulation with the new values, call <span style=\" font-family:\'Courier New,courier\';\">simulation.Reinitialize()</span> and close this form.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonUpdateSimulationAndClose.setText(QtGui.QApplication.translate("SimulationExplorer", "Update and close", None, QtGui.QApplication.UnicodeUTF8))

