# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Simulator.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SimulatorDialog(object):
    def setupUi(self, SimulatorDialog):
        SimulatorDialog.setObjectName("SimulatorDialog")
        SimulatorDialog.resize(700, 580)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SimulatorDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.simulationLabel = QtWidgets.QLabel(SimulatorDialog)
        self.simulationLabel.setObjectName("simulationLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.simulationLabel)
        self.SimulationLineEdit = QtWidgets.QLineEdit(SimulatorDialog)
        self.SimulationLineEdit.setEnabled(False)
        self.SimulationLineEdit.setObjectName("SimulationLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.SimulationLineEdit)
        self.DataReporterTCPIPAddressLabel = QtWidgets.QLabel(SimulatorDialog)
        self.DataReporterTCPIPAddressLabel.setObjectName("DataReporterTCPIPAddressLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.DataReporterTCPIPAddressLabel)
        self.DataReporterTCPIPAddressLineEdit = QtWidgets.QLineEdit(SimulatorDialog)
        self.DataReporterTCPIPAddressLineEdit.setText("")
        self.DataReporterTCPIPAddressLineEdit.setObjectName("DataReporterTCPIPAddressLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.DataReporterTCPIPAddressLineEdit)
        self.MINLPSolverLabel = QtWidgets.QLabel(SimulatorDialog)
        self.MINLPSolverLabel.setObjectName("MINLPSolverLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.MINLPSolverLabel)
        self.MINLPSolverComboBox = QtWidgets.QComboBox(SimulatorDialog)
        self.MINLPSolverComboBox.setObjectName("MINLPSolverComboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.MINLPSolverComboBox)
        self.DAESolverLabel = QtWidgets.QLabel(SimulatorDialog)
        self.DAESolverLabel.setObjectName("DAESolverLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.DAESolverLabel)
        self.DAESolverComboBox = QtWidgets.QComboBox(SimulatorDialog)
        self.DAESolverComboBox.setObjectName("DAESolverComboBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.DAESolverComboBox)
        self.LASolverLabel = QtWidgets.QLabel(SimulatorDialog)
        self.LASolverLabel.setObjectName("LASolverLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.LASolverLabel)
        self.LASolverComboBox = QtWidgets.QComboBox(SimulatorDialog)
        self.LASolverComboBox.setObjectName("LASolverComboBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LASolverComboBox)
        self.TimeHorizonLabel = QtWidgets.QLabel(SimulatorDialog)
        self.TimeHorizonLabel.setObjectName("TimeHorizonLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.TimeHorizonLabel)
        self.TimeHorizonDoubleSpinBox = QtWidgets.QDoubleSpinBox(SimulatorDialog)
        self.TimeHorizonDoubleSpinBox.setDecimals(5)
        self.TimeHorizonDoubleSpinBox.setMaximum(1000000000.0)
        self.TimeHorizonDoubleSpinBox.setObjectName("TimeHorizonDoubleSpinBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.TimeHorizonDoubleSpinBox)
        self.ReportingIntervalLabel = QtWidgets.QLabel(SimulatorDialog)
        self.ReportingIntervalLabel.setObjectName("ReportingIntervalLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.ReportingIntervalLabel)
        self.ReportingIntervalDoubleSpinBox = QtWidgets.QDoubleSpinBox(SimulatorDialog)
        self.ReportingIntervalDoubleSpinBox.setDecimals(5)
        self.ReportingIntervalDoubleSpinBox.setMaximum(1000000000.0)
        self.ReportingIntervalDoubleSpinBox.setObjectName("ReportingIntervalDoubleSpinBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.ReportingIntervalDoubleSpinBox)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.ExportButton = QtWidgets.QPushButton(SimulatorDialog)
        self.ExportButton.setEnabled(True)
        self.ExportButton.setObjectName("ExportButton")
        self.horizontalLayout.addWidget(self.ExportButton)
        self.MatrixButton = QtWidgets.QPushButton(SimulatorDialog)
        self.MatrixButton.setEnabled(True)
        self.MatrixButton.setObjectName("MatrixButton")
        self.horizontalLayout.addWidget(self.MatrixButton)
        self.RunButton = QtWidgets.QPushButton(SimulatorDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RunButton.sizePolicy().hasHeightForWidth())
        self.RunButton.setSizePolicy(sizePolicy)
        self.RunButton.setDefault(True)
        self.RunButton.setObjectName("RunButton")
        self.horizontalLayout.addWidget(self.RunButton)
        self.PauseButton = QtWidgets.QPushButton(SimulatorDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PauseButton.sizePolicy().hasHeightForWidth())
        self.PauseButton.setSizePolicy(sizePolicy)
        self.PauseButton.setObjectName("PauseButton")
        self.horizontalLayout.addWidget(self.PauseButton)
        self.ResumeButton = QtWidgets.QPushButton(SimulatorDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResumeButton.sizePolicy().hasHeightForWidth())
        self.ResumeButton.setSizePolicy(sizePolicy)
        self.ResumeButton.setCheckable(False)
        self.ResumeButton.setChecked(False)
        self.ResumeButton.setObjectName("ResumeButton")
        self.horizontalLayout.addWidget(self.ResumeButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(SimulatorDialog)
        self.textEdit.setEnabled(True)
        self.textEdit.setMinimumSize(QtCore.QSize(510, 180))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        self.textEdit.setFont(font)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit.setUndoRedoEnabled(False)
        self.textEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit.setReadOnly(True)
        self.textEdit.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Monospace\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Courier New\';\"><br /></p></body></html>")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.progressBar = QtWidgets.QProgressBar(SimulatorDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(150, 0))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)
        self.progressLabel = QtWidgets.QLabel(SimulatorDialog)
        self.progressLabel.setText("")
        self.progressLabel.setObjectName("progressLabel")
        self.horizontalLayout_3.addWidget(self.progressLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(SimulatorDialog)
        QtCore.QMetaObject.connectSlotsByName(SimulatorDialog)

    def retranslateUi(self, SimulatorDialog):
        _translate = QtCore.QCoreApplication.translate
        SimulatorDialog.setWindowTitle(_translate("SimulatorDialog", "DAE Tools Simulator"))
        self.simulationLabel.setText(_translate("SimulatorDialog", "Simulation"))
        self.DataReporterTCPIPAddressLabel.setText(_translate("SimulatorDialog", "Data Reporter (TCP/IP : port)"))
        self.MINLPSolverLabel.setText(_translate("SimulatorDialog", "(MI)NLP Solver"))
        self.DAESolverLabel.setText(_translate("SimulatorDialog", "DAE Solver"))
        self.LASolverLabel.setText(_translate("SimulatorDialog", "LA Solver"))
        self.TimeHorizonLabel.setText(_translate("SimulatorDialog", "Time Horizon, s"))
        self.ReportingIntervalLabel.setText(_translate("SimulatorDialog", "Reporting Interval, s"))
        self.ExportButton.setText(_translate("SimulatorDialog", "Export Matrix..."))
        self.MatrixButton.setText(_translate("SimulatorDialog", "Matrix Preview..."))
        self.RunButton.setText(_translate("SimulatorDialog", "Start..."))
        self.PauseButton.setText(_translate("SimulatorDialog", "Pause"))
        self.ResumeButton.setText(_translate("SimulatorDialog", "Resume"))

