# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choose_variable.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ChooseVariable(object):
    def setupUi(self, ChooseVariable):
        ChooseVariable.setObjectName("ChooseVariable")
        ChooseVariable.resize(660, 497)
        ChooseVariable.setSizeGripEnabled(True)
        ChooseVariable.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ChooseVariable)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(ChooseVariable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(350, 300))
        self.treeWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.treeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.treeWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeWidget.setTabKeyNavigation(True)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setColumnCount(1)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.treeWidget.header().setVisible(False)
        self.treeWidget.header().setDefaultSectionSize(400)
        self.horizontalLayout.addWidget(self.treeWidget)
        self.widget = QtWidgets.QWidget(ChooseVariable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(200, 0))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(6, 6, 6, 6)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.domain0Label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domain0Label.sizePolicy().hasHeightForWidth())
        self.domain0Label.setSizePolicy(sizePolicy)
        self.domain0Label.setMinimumSize(QtCore.QSize(100, 0))
        self.domain0Label.setWordWrap(True)
        self.domain0Label.setObjectName("domain0Label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.domain0Label)
        self.domain0ComboBox = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domain0ComboBox.sizePolicy().hasHeightForWidth())
        self.domain0ComboBox.setSizePolicy(sizePolicy)
        self.domain0ComboBox.setMinimumSize(QtCore.QSize(50, 0))
        self.domain0ComboBox.setObjectName("domain0ComboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.domain0ComboBox)
        self.domain1Label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domain1Label.sizePolicy().hasHeightForWidth())
        self.domain1Label.setSizePolicy(sizePolicy)
        self.domain1Label.setMinimumSize(QtCore.QSize(100, 0))
        self.domain1Label.setWordWrap(True)
        self.domain1Label.setObjectName("domain1Label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.domain1Label)
        self.domain1ComboBox = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domain1ComboBox.sizePolicy().hasHeightForWidth())
        self.domain1ComboBox.setSizePolicy(sizePolicy)
        self.domain1ComboBox.setMinimumSize(QtCore.QSize(50, 0))
        self.domain1ComboBox.setObjectName("domain1ComboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.domain1ComboBox)
        self.domain2Label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domain2Label.sizePolicy().hasHeightForWidth())
        self.domain2Label.setSizePolicy(sizePolicy)
        self.domain2Label.setMinimumSize(QtCore.QSize(100, 0))
        self.domain2Label.setWordWrap(True)
        self.domain2Label.setObjectName("domain2Label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.domain2Label)
        self.domain2ComboBox = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domain2ComboBox.sizePolicy().hasHeightForWidth())
        self.domain2ComboBox.setSizePolicy(sizePolicy)
        self.domain2ComboBox.setMinimumSize(QtCore.QSize(50, 0))
        self.domain2ComboBox.setObjectName("domain2ComboBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.domain2ComboBox)
        self.domain3Label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domain3Label.sizePolicy().hasHeightForWidth())
        self.domain3Label.setSizePolicy(sizePolicy)
        self.domain3Label.setMinimumSize(QtCore.QSize(100, 0))
        self.domain3Label.setWordWrap(True)
        self.domain3Label.setObjectName("domain3Label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.domain3Label)
        self.domain3ComboBox = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domain3ComboBox.sizePolicy().hasHeightForWidth())
        self.domain3ComboBox.setSizePolicy(sizePolicy)
        self.domain3ComboBox.setMinimumSize(QtCore.QSize(50, 0))
        self.domain3ComboBox.setObjectName("domain3ComboBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.domain3ComboBox)
        self.domain4Label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domain4Label.sizePolicy().hasHeightForWidth())
        self.domain4Label.setSizePolicy(sizePolicy)
        self.domain4Label.setMinimumSize(QtCore.QSize(100, 0))
        self.domain4Label.setWordWrap(True)
        self.domain4Label.setObjectName("domain4Label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.domain4Label)
        self.domain4ComboBox = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.domain4ComboBox.sizePolicy().hasHeightForWidth())
        self.domain4ComboBox.setSizePolicy(sizePolicy)
        self.domain4ComboBox.setMinimumSize(QtCore.QSize(50, 0))
        self.domain4ComboBox.setObjectName("domain4ComboBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.domain4ComboBox)
        self.timeLabel = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeLabel.sizePolicy().hasHeightForWidth())
        self.timeLabel.setSizePolicy(sizePolicy)
        self.timeLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.timeLabel.setObjectName("timeLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.timeLabel)
        self.timeComboBox = QtWidgets.QComboBox(self.widget)
        self.timeComboBox.setMinimumSize(QtCore.QSize(50, 0))
        self.timeComboBox.setObjectName("timeComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.timeComboBox)
        self.domain5Label = QtWidgets.QLabel(self.widget)
        self.domain5Label.setObjectName("domain5Label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.domain5Label)
        self.domain5ComboBox = QtWidgets.QComboBox(self.widget)
        self.domain5ComboBox.setMinimumSize(QtCore.QSize(50, 0))
        self.domain5ComboBox.setObjectName("domain5ComboBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.domain5ComboBox)
        self.domain6Label = QtWidgets.QLabel(self.widget)
        self.domain6Label.setObjectName("domain6Label")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.domain6Label)
        self.domain6ComboBox = QtWidgets.QComboBox(self.widget)
        self.domain6ComboBox.setMinimumSize(QtCore.QSize(50, 0))
        self.domain6ComboBox.setObjectName("domain6ComboBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.domain6ComboBox)
        self.domain7Label = QtWidgets.QLabel(self.widget)
        self.domain7Label.setObjectName("domain7Label")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.domain7Label)
        self.domain7ComboBox = QtWidgets.QComboBox(self.widget)
        self.domain7ComboBox.setMinimumSize(QtCore.QSize(50, 0))
        self.domain7ComboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.domain7ComboBox.setObjectName("domain7ComboBox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.domain7ComboBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.buttonCancel = QtWidgets.QPushButton(ChooseVariable)
        self.buttonCancel.setObjectName("buttonCancel")
        self.horizontalLayout_2.addWidget(self.buttonCancel)
        self.buttonOk = QtWidgets.QPushButton(ChooseVariable)
        self.buttonOk.setDefault(True)
        self.buttonOk.setObjectName("buttonOk")
        self.horizontalLayout_2.addWidget(self.buttonOk)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ChooseVariable)
        self.domain0ComboBox.setCurrentIndex(-1)
        self.domain1ComboBox.setCurrentIndex(-1)
        self.buttonCancel.clicked.connect(ChooseVariable.reject)
        self.buttonOk.clicked.connect(ChooseVariable.accept)
        QtCore.QMetaObject.connectSlotsByName(ChooseVariable)
        ChooseVariable.setTabOrder(self.treeWidget, self.domain0ComboBox)
        ChooseVariable.setTabOrder(self.domain0ComboBox, self.domain1ComboBox)
        ChooseVariable.setTabOrder(self.domain1ComboBox, self.domain2ComboBox)
        ChooseVariable.setTabOrder(self.domain2ComboBox, self.domain3ComboBox)
        ChooseVariable.setTabOrder(self.domain3ComboBox, self.domain4ComboBox)

    def retranslateUi(self, ChooseVariable):
        _translate = QtCore.QCoreApplication.translate
        ChooseVariable.setWindowTitle(_translate("ChooseVariable", "Choose variable"))
        self.domain0Label.setText(_translate("ChooseVariable", "Domain0"))
        self.domain1Label.setText(_translate("ChooseVariable", "Domain1"))
        self.domain2Label.setText(_translate("ChooseVariable", "Domain2"))
        self.domain3Label.setText(_translate("ChooseVariable", "Domain3"))
        self.domain4Label.setText(_translate("ChooseVariable", "Domain4"))
        self.timeLabel.setText(_translate("ChooseVariable", "Time"))
        self.domain5Label.setText(_translate("ChooseVariable", "Domain5"))
        self.domain6Label.setText(_translate("ChooseVariable", "Domain6"))
        self.domain7Label.setText(_translate("ChooseVariable", "Domain7"))
        self.buttonCancel.setText(_translate("ChooseVariable", "Cancel"))
        self.buttonOk.setText(_translate("ChooseVariable", "Ok"))

